services:
  dev:
    image: ghcr.io/ctison/dev:latest
    build:
      context: ..
      x-bake:
        attest:
          - type=sbom
          - type=provenance
        cache-to:
          - type=registry,ref=ghcr.io/ctison/dev:cache,mode=max
        cache-from:
          - type=registry,ref=ghcr.io/ctison/dev:cache
        platforms:
          - linux/amd64
          - linux/arm64
