[tools]
bun = '1'

eza = 'latest'
gh = 'latest'
duf = 'latest'
dust = { os = ['darwin'], version = 'latest' }
fd = 'latest'
lazygit = 'latest'
shellcheck = 'latest'
xh = 'latest'
starship = 'latest'
bat = 'latest'
ripgrep = 'latest'
zellij = 'latest'

[settings]
unix_default_file_shell_args = 'bash -euo pipefail -O nullglob'

[tasks.ci]
run = '''
bun install --frozen-lockfile
bun run format:check
bun run test
'''
