# format = '''
# [\[](bold white)[$username@$hostname](bold green)[\]](bold white) [$directory](bold blue)
# [λ](bold red)
# '''

[directory]
truncation_length = 0
truncate_to_repo = false
style = 'bold blue'

[status]
disabled = false
# map_symbol = true

[git_branch]
format = '[(\($branch\))]($style)'
style = 'bold red'

[git_status]
disabled = true

[character]
success_symbol = '[λ](bold red)'

[cmd_duration]
min_time = 1_000
show_milliseconds = true

# [aws]
# format = '[( aws:$profile)]($style)'
# style = 'bold black'
# [aws.region_aliases]
# ap-southeast-2 = "au"
# eu-west-3 = 'eu3'
# us-east-1 = "va"

# [docker_context]
# only_with_files = false
# format = '[( docker:$context)]($style)'
# style = 'bold black'

# [gcloud]
# format = '[( gcp:$account)]($style)'
# style = 'bold black dimmed'
# disabled = true

# [golang]
# disabled = true

# [helm]
# disabled = true

# [hostname]
# # ssh_only = false
# style = 'bold green'

# [kubernetes]
# disabled = false
# format = '[( k8s:$context(:$namespace))]($style)'
# style = 'bold black'

# [nodejs]
# format = '[( node:$version)]($style)'
# style = 'bold black'
