[directory]
read_only = ' '
truncate_to_repo = false
truncation_length = 0

[status]
disabled = false
map_symbol = true

[time]
disabled = false

[git_branch]
format = '[$symbol$branch]($style) '
symbol = ' '

[character]
success_symbol = '[λ](bold red)'

[cmd_duration]
show_milliseconds = true
show_notifications = true

[aws]
format = '[$symbol$profile($region)]($style)'
symbol = '  '

[conda]
symbol = ' '

[dart]
symbol = ' '

[docker]
symbol = ' '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[golang]
symbol = ' '

[haskell]
symbol = ' '

[hg_branch]
symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[memory_usage]
symbol = ' '

[nim]
symbol = ' '

[nix_shell]
symbol = ' '

[nodejs]
format = '[$symbol($version )]($style)'
symbol = ' '

[package]
symbol = ' '

[perl]
symbol = ' '

[php]
symbol = ' '

[python]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[swift]
symbol = 'ﯣ '

[custom.k8s]
command = '''
'''

[kubernetes]
disabled = false
