set nocompatible
set number
set ruler
set mouse=a
set wildmenu
set hlsearch

set shell=/bin/bash

" Status bar (at bottom)
set laststatus=2
hi StatusLine ctermbg=blue ctermfg=yellow

" Syntax coloring
syntax on
colorscheme delek

autocmd FileType python colorscheme zellner

" Toggle paste mode
set pastetoggle=<F10>

" Disable logging
set viminfo=

" Map backspace
set backspace=indent,eol,start

" https://vim.fandom.com/wiki/Indenting_source_code
set tabstop=2
set shiftwidth=2
set softtabstop=0
set noexpandtab
set autoindent
set nosmartindent