[tools]
ripgrep = 'latest'
bat = 'latest'
duf = 'latest'
eza = 'latest'
fd = 'latest'
gh = 'latest'
lazygit = 'latest'
starship = 'latest'
xh = 'latest'

[settings]
auto_install = false

unix_default_file_shell_args = 'bash -euo pipefail -O nullglob'
unix_default_inline_shell_args = 'bash -euo pipefail -O nullglob -c'

[settings.npm]
bun = true

[settings.status]
missing_tools = 'always'
show_env = true
show_tools = true
