# yaml-language-server: $schema=https://raw.githubusercontent.com/rancher/k3d/main/pkg/config/v1alpha4/schema.json
apiVersion: k3d.io/v1alpha4
kind: Simple
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
