name: CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4
      - uses: jdx/mise-action@v2
      - name: Lint
        run: |
          bun install --frozen-lockfile
          bun run format:check
          bun tsc

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v6
        with:
          source: .
          workdir: .github/
          pull: true
          push: true
