name: Docker

on:
  push:
    branches: [master]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Build and push ctison/ubuntu
        uses: docker/build-push-action@v2.0.1
        with:
          repository: ctison/ubuntu
          target: ubuntu
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
          username: ctison
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push ctison/kali
        uses: docker/build-push-action@v2.0.1
        with:
          repository: ctison/kali
          target: kali
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
          username: ctison
          password: ${{secrets.DOCKERHUB_PASSWORD}}
