name: Docker

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch:
    inputs:
      deploy:
        description: Set to `true` to deploy to K8s
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      # Compute a should-deploy boolean value
      - name: Compute `should-deploy` boolean value
        id: should-deploy
        run: |
          echo ::set-output name=value::${{ github.ref == 'refs/heads/main' || github.event.inputs.deploy == 'true' }}

      - if: steps.should-deploy.outputs.value == 'true'
        uses: docker/login-action@v1
        with:
          username: ctison
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Cache the Docker layers
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/build-push-action@v2
        with:
          tags: ctison/ubuntu
          target: ubuntu
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: ${{ steps.should-deploy.outputs.value == 'true' }}

      - uses: docker/build-push-action@v2
        with:
          tags: ctison/kali
          target: kali
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          push: ${{ steps.should-deploy.outputs.value == 'true' }}
